language: node_js
node_js:
- node
- '9'
stages:
- test
- qualify
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: qualify
    script:
    - npm run test-ci
    services:
    - mongodb
    before_script:
    - sleep 15
    - mongo images-hunter --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: Ua0VtKq70HxObm1vJargsxIgZiPYhTYFTRYHly3aeg+royQt502yRspMOMmNyBMk8MKgKPiKOi2CXZ9XuaF1UveiDEXm6pS6zHl+kaMpENAgUmbL+SOW0rSQIG0Pn2azbDSKYTTDWLBgRdj0hyROxJtMO5SqasuwTN/ZYe2FvQV96Z66yNLEo+9NUDVdfMU9UQ0UsMfYivlyF2pDvr7YRIVXHsMXjAMO8lQtxGoa5b9PdF63z89zav1ulMz1k3QERK2OKj/LbdJq+AA17RP+BVMqAVp4/9NvovflmyNjGBt7Zv7mgHT8YzeCwjROsN6nIlzPhqoBAskTneWoGrdxoQPKD/D3JDGdBe2BPSKYAY7hWhi/m7G1kzt5XA5lVvAjY1NggVaNriI7Z7yUj2M10ZI0VWx1iZLi0ImD6T0EDelAc+sx4YzCj4OWzXVFVFV+u6NpDwe5DVbisIH/uYioXwXwzeCgZDvh7M5gncMpbPMvuJop5kGw+Dk5USsXxgU4mLzB8KFRDUtVy38Q3jrHQ581E/WpeESj1T6dQtR3ExPV9ClwzhqcoVZSo54L6yFldOFEvHhrQZ5JkecsjRueGVIK3z46Coc6hoHmR5+OFo+EIbWdMhEK9U7BxccMEbz8EwMMZI8HVYTznZ7QmCyeaBRj2v+P/hxrLP05oSs3lLA=
      app: shrouded-caverns-57885
      stage: deploy
